# Generated by Django 5.1.3 on 2025-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=225)),
                ('volume', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
            ],
        ),
    ]
