# Generated by Django 5.1.3 on 2025-01-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_device_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
