# Generated by Django 5.1.1 on 2024-10-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_device_behavioralpattern_anomaly_networktraffic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packet',
        ),
    ]
