# Generated by Django 5.1.4 on 2025-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_device_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
