# Generated by Django 5.1.3 on 2025-01-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_device_training_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='training_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
