# Generated by Django 5.1.3 on 2025-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
