# Generated by Django 5.1.3 on 2025-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_notification_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
