# Generated by Django 5.1.3 on 2025-01-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
