# Generated by Django 5.1.3 on 2025-01-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_minutes', models.IntegerField(default=60)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='number_of_users',
            field=models.IntegerField(default=1),
        ),
    ]
