# Generated by Django 5.1.3 on 2025-01-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_settings_device_number_of_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
