# Generated by Django 5.1.3 on 2025-01-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_rename_settings_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
