# Generated by Django 5.1.3 on 2025-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_device_is_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='frequency',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='traffic_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True),
        ),
    ]
