# Generated by Django 5.1.3 on 2025-02-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_device_frequency_device_traffic_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='frequency',
        ),
        migrations.AddField(
            model_name='device',
            name='protocols',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='device',
            name='traffic_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
