# Generated by Django 5.1.3 on 2025-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_device_frequency_device_protocols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connected_ips',
            field=models.JSONField(default=dict),
        ),
    ]
