# Generated by Django 5.1.3 on 2025-02-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_device_connected_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='traffic_volume',
        ),
    ]
