# Generated by Django 5.1.3 on 2025-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_remove_device_traffic_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
