# Generated by Django 5.1.3 on 2025-02-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connected_ips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocols',
            field=models.JSONField(default=list),
        ),
    ]
