# Generated by Django 5.1.3 on 2025-02-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_device_connected_ips_alter_device_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.device'),
        ),
    ]
