# Generated by Django 5.1.3 on 2025-02-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_notification_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parameter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
